### ISSUE TITLE
Gradm 2.x

### ISSUE THREAD

**Issue by Omico** [Omico/Gradm#3]
**May be changed at any time**

## Accomplished

<details>
<summary> More compact format for config (#7) </summary>
</p>

This new format will take advantage of IDEs' language check to prevent duplicate definitions. Also, this will remove more restrictions on aliases.

```yaml
repositories:
  google:
    url: https://maven.google.com/
  mavenCentral:
    url: https://repo1.maven.org/maven2/

dependencies:
  mavenCentral:
    com.google.accompanist:
      accompanist-insets:
        alias: accompanist.insets
        version: ${versions.accompanist}
      accompanist-insets-ui:
        alias: accompanist.insetsUi
        version: ${versions.accompanist}
      accompanist-permissions:
        alias: accompanist.permissions
        version: ${versions.accompanist}
      accompanist-swiperefresh:
        alias: accompanist.swipeRefresh
        version: ${versions.accompanist}
      accompanist-systemuicontroller:
        alias: accompanist.systemUiController
        version: ${versions.accompanist}
    com.squareup.okhttp3:
      logging-interceptor:
        alias: okhttp3.interceptor.logging
        version: ${versions.okhttp}
      okhttp3:
        alias: okhttp3
        version: ${versions.okhttp}
      okhttp-dnsoverhttps:
        alias: okhttp3.dnsOverHttps
        version: ${versions.okhttp}
```
</details>
