### ISSUE TITLE
Supports unseparated independent alias

### ISSUE THREAD

**Issue by Omico** [Omico/Gradm#8]
Currently, Gradm doesn't support unseparated independent alias.

For example:

```yaml
dependencies:
  google:
    com.google.android.material:
      material:
        alias: material # codegen issue here
        version: ${versions.material}
```

You can use the below code as a workaround:

```yaml
dependencies:
  google:
    com.google.android.material:
      material:
        alias: google.material # works as long as alias contains a dot (or more than one dot)
        version: ${versions.material}
```
