### ISSUE TITLE
Remove more restrictions on versions

### ISSUE THREAD

**Issue by Omico** [Omico/Gradm#9]
Currently, Gradm doesn't support the below config in `gradm.yaml`:
```yaml
versions:
  androidx:
    compose: "1.2.0-beta03" # supported, versions.androidx.compose
    composeMaterial3: "1.0.0-alpha13" # supported, versions.androidx.composeMaterial3
    compose-material3: "1.0.0-alpha13" # unsupported, expect: versions.androidx.compose.material3
    compose.material3: "1.0.0-alpha13" # unsupported, expect: versions.androidx.compose.material3
```
